### PR TITLE
Make plugin to a composer package

### PR DESCRIPTION
**Pull request by breaker92**
@conexco if you register this repo on https://packagist.org/ the repository documentation is unnecessary.

### CODE REVIEW

**Comment by shyim** [comment]
It would be nice if you fill all fields like "authors" and  "license"

**Comment by breaker92** [comment]
I add some additional fields.

**Comment by FalkoHilbert** [comment]
@oktupol @benjamin-ott 
please merge, i would use it as composer depency

**Comment by uehler** [comment]
Hi @breaker92,

first of all, thank you for your contribution and sorry for the inactivity on this PR!

You can't install plugins as composer dependency as of Shopware 5.3 as far as I now. In order to achieve that, you need @shyim's packagist plugin (https://github.com/shyim/ShyimPluginManager). Correct? In that case please update the instruction and add a link to that plugin.

After that I will merge your PR.

**Comment by shyim** [comment]
@uehler Its a easier way to install it, so composer req in shopware root works also 😊

**Comment by uehler** [comment]
@shyim but I need your plugin in order to put the theme in the correct directory?

**Comment by viosys** [comment]
@uehler no `"type": "shopware-plugin"` ensures that the correct plugin directory is addressed

**Comment by uehler** [comment]
ok, we didn't knew that this works out of the box.

Great!
We will register the plugin at packagist and will merge this PR.

Stay tuned!

**Comment by uehler** [comment]
@breaker92 thank you for your contribution!
@shyim @FalkoHilbert @viosys thank you for your help

Happy coding! 🎉

**Pull request merged**
